on:
  push:
    paths:
      - AssetFolder/**/*
  workflow_dispatch:

jobs:
    convert_to_csv:
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Clone https://github.com/SaltContainer/Lumi_Small_Scripts
          uses: actions/checkout@v4
          with:
            repository: SaltContainer/Lumi_Small_Scripts
            path: Lumi_Small_Scripts
        - name: Create input and output folders
          run: mkdir -p input output
          working-directory: Lumi_Small_Scripts/label_files
        - name: Copy files
          run: cp -r $GITHUB_WORKSPACE/AssetFolder/* input
          working-directory: Lumi_Small_Scripts/label_files
        - name: Override conversion script
          run: cp $GITHUB_WORKSPACE/overrides/convert.py .
          working-directory: Lumi_Small_Scripts/label_files
        - name: Convert to CSV
          run: python convert.py csv
          working-directory: Lumi_Small_Scripts/label_files
        - name: Copy output files
          run: cp output/* $GITHUB_WORKSPACE/csv
          working-directory: Lumi_Small_Scripts/label_files
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Convert changed files to CSV"
            branch: main
            file_pattern: 'csv/*'